package com.guo.shopcart.dao;

import com.guo.client.model.shopcart.ShopCartDO;
import com.guo.client.model.shopcart.ShopCartDOExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ShopCartDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_cart
     *
     * @mbg.generated
     */
    long countByExample(ShopCartDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_cart
     *
     * @mbg.generated
     */
    int deleteByExample(ShopCartDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_cart
     *
     * @mbg.generated
     */
    int insert(ShopCartDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_cart
     *
     * @mbg.generated
     */
    int insertSelective(ShopCartDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_cart
     *
     * @mbg.generated
     */
    List<ShopCartDO> selectByExample(ShopCartDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_cart
     *
     * @mbg.generated
     */
    ShopCartDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopCartDO record, @Param("example") ShopCartDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopCartDO record, @Param("example") ShopCartDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopCartDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopCartDO record);

    List<ShopCartDO> queryAllByUserId(String userId);

    List<ShopCartDO> queryAllShopCartInId(@Param("ids") List<Long> ids);

    int removerShopCartInIdsR(@Param("ids")List<Long> ids);
}