package com.guo.client.model.commodity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CommodityModelDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_commodity_model
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_commodity_model
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_commodity_model
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity_model
     *
     * @mbg.generated
     */
    public CommodityModelDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity_model
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity_model
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity_model
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity_model
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity_model
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity_model
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity_model
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity_model
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity_model
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity_model
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_commodity_model
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCommodityIdIsNull() {
            addCriterion("commodity_id is null");
            return (Criteria) this;
        }

        public Criteria andCommodityIdIsNotNull() {
            addCriterion("commodity_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityIdEqualTo(String value) {
            addCriterion("commodity_id =", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdNotEqualTo(String value) {
            addCriterion("commodity_id <>", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdGreaterThan(String value) {
            addCriterion("commodity_id >", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdGreaterThanOrEqualTo(String value) {
            addCriterion("commodity_id >=", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdLessThan(String value) {
            addCriterion("commodity_id <", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdLessThanOrEqualTo(String value) {
            addCriterion("commodity_id <=", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdLike(String value) {
            addCriterion("commodity_id like", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdNotLike(String value) {
            addCriterion("commodity_id not like", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdIn(List<String> values) {
            addCriterion("commodity_id in", values, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdNotIn(List<String> values) {
            addCriterion("commodity_id not in", values, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdBetween(String value1, String value2) {
            addCriterion("commodity_id between", value1, value2, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdNotBetween(String value1, String value2) {
            addCriterion("commodity_id not between", value1, value2, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityModelIdIsNull() {
            addCriterion("commodity_model_id is null");
            return (Criteria) this;
        }

        public Criteria andCommodityModelIdIsNotNull() {
            addCriterion("commodity_model_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityModelIdEqualTo(String value) {
            addCriterion("commodity_model_id =", value, "commodityModelId");
            return (Criteria) this;
        }

        public Criteria andCommodityModelIdNotEqualTo(String value) {
            addCriterion("commodity_model_id <>", value, "commodityModelId");
            return (Criteria) this;
        }

        public Criteria andCommodityModelIdGreaterThan(String value) {
            addCriterion("commodity_model_id >", value, "commodityModelId");
            return (Criteria) this;
        }

        public Criteria andCommodityModelIdGreaterThanOrEqualTo(String value) {
            addCriterion("commodity_model_id >=", value, "commodityModelId");
            return (Criteria) this;
        }

        public Criteria andCommodityModelIdLessThan(String value) {
            addCriterion("commodity_model_id <", value, "commodityModelId");
            return (Criteria) this;
        }

        public Criteria andCommodityModelIdLessThanOrEqualTo(String value) {
            addCriterion("commodity_model_id <=", value, "commodityModelId");
            return (Criteria) this;
        }

        public Criteria andCommodityModelIdLike(String value) {
            addCriterion("commodity_model_id like", value, "commodityModelId");
            return (Criteria) this;
        }

        public Criteria andCommodityModelIdNotLike(String value) {
            addCriterion("commodity_model_id not like", value, "commodityModelId");
            return (Criteria) this;
        }

        public Criteria andCommodityModelIdIn(List<String> values) {
            addCriterion("commodity_model_id in", values, "commodityModelId");
            return (Criteria) this;
        }

        public Criteria andCommodityModelIdNotIn(List<String> values) {
            addCriterion("commodity_model_id not in", values, "commodityModelId");
            return (Criteria) this;
        }

        public Criteria andCommodityModelIdBetween(String value1, String value2) {
            addCriterion("commodity_model_id between", value1, value2, "commodityModelId");
            return (Criteria) this;
        }

        public Criteria andCommodityModelIdNotBetween(String value1, String value2) {
            addCriterion("commodity_model_id not between", value1, value2, "commodityModelId");
            return (Criteria) this;
        }

        public Criteria andCommodityModelNameIsNull() {
            addCriterion("commodity_model_name is null");
            return (Criteria) this;
        }

        public Criteria andCommodityModelNameIsNotNull() {
            addCriterion("commodity_model_name is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityModelNameEqualTo(String value) {
            addCriterion("commodity_model_name =", value, "commodityModelName");
            return (Criteria) this;
        }

        public Criteria andCommodityModelNameNotEqualTo(String value) {
            addCriterion("commodity_model_name <>", value, "commodityModelName");
            return (Criteria) this;
        }

        public Criteria andCommodityModelNameGreaterThan(String value) {
            addCriterion("commodity_model_name >", value, "commodityModelName");
            return (Criteria) this;
        }

        public Criteria andCommodityModelNameGreaterThanOrEqualTo(String value) {
            addCriterion("commodity_model_name >=", value, "commodityModelName");
            return (Criteria) this;
        }

        public Criteria andCommodityModelNameLessThan(String value) {
            addCriterion("commodity_model_name <", value, "commodityModelName");
            return (Criteria) this;
        }

        public Criteria andCommodityModelNameLessThanOrEqualTo(String value) {
            addCriterion("commodity_model_name <=", value, "commodityModelName");
            return (Criteria) this;
        }

        public Criteria andCommodityModelNameLike(String value) {
            addCriterion("commodity_model_name like", value, "commodityModelName");
            return (Criteria) this;
        }

        public Criteria andCommodityModelNameNotLike(String value) {
            addCriterion("commodity_model_name not like", value, "commodityModelName");
            return (Criteria) this;
        }

        public Criteria andCommodityModelNameIn(List<String> values) {
            addCriterion("commodity_model_name in", values, "commodityModelName");
            return (Criteria) this;
        }

        public Criteria andCommodityModelNameNotIn(List<String> values) {
            addCriterion("commodity_model_name not in", values, "commodityModelName");
            return (Criteria) this;
        }

        public Criteria andCommodityModelNameBetween(String value1, String value2) {
            addCriterion("commodity_model_name between", value1, value2, "commodityModelName");
            return (Criteria) this;
        }

        public Criteria andCommodityModelNameNotBetween(String value1, String value2) {
            addCriterion("commodity_model_name not between", value1, value2, "commodityModelName");
            return (Criteria) this;
        }

        public Criteria andCommodityModelInfoIsNull() {
            addCriterion("commodity_model_info is null");
            return (Criteria) this;
        }

        public Criteria andCommodityModelInfoIsNotNull() {
            addCriterion("commodity_model_info is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityModelInfoEqualTo(String value) {
            addCriterion("commodity_model_info =", value, "commodityModelInfo");
            return (Criteria) this;
        }

        public Criteria andCommodityModelInfoNotEqualTo(String value) {
            addCriterion("commodity_model_info <>", value, "commodityModelInfo");
            return (Criteria) this;
        }

        public Criteria andCommodityModelInfoGreaterThan(String value) {
            addCriterion("commodity_model_info >", value, "commodityModelInfo");
            return (Criteria) this;
        }

        public Criteria andCommodityModelInfoGreaterThanOrEqualTo(String value) {
            addCriterion("commodity_model_info >=", value, "commodityModelInfo");
            return (Criteria) this;
        }

        public Criteria andCommodityModelInfoLessThan(String value) {
            addCriterion("commodity_model_info <", value, "commodityModelInfo");
            return (Criteria) this;
        }

        public Criteria andCommodityModelInfoLessThanOrEqualTo(String value) {
            addCriterion("commodity_model_info <=", value, "commodityModelInfo");
            return (Criteria) this;
        }

        public Criteria andCommodityModelInfoLike(String value) {
            addCriterion("commodity_model_info like", value, "commodityModelInfo");
            return (Criteria) this;
        }

        public Criteria andCommodityModelInfoNotLike(String value) {
            addCriterion("commodity_model_info not like", value, "commodityModelInfo");
            return (Criteria) this;
        }

        public Criteria andCommodityModelInfoIn(List<String> values) {
            addCriterion("commodity_model_info in", values, "commodityModelInfo");
            return (Criteria) this;
        }

        public Criteria andCommodityModelInfoNotIn(List<String> values) {
            addCriterion("commodity_model_info not in", values, "commodityModelInfo");
            return (Criteria) this;
        }

        public Criteria andCommodityModelInfoBetween(String value1, String value2) {
            addCriterion("commodity_model_info between", value1, value2, "commodityModelInfo");
            return (Criteria) this;
        }

        public Criteria andCommodityModelInfoNotBetween(String value1, String value2) {
            addCriterion("commodity_model_info not between", value1, value2, "commodityModelInfo");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIsNull() {
            addCriterion("unit_price is null");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIsNotNull() {
            addCriterion("unit_price is not null");
            return (Criteria) this;
        }

        public Criteria andUnitPriceEqualTo(Double value) {
            addCriterion("unit_price =", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotEqualTo(Double value) {
            addCriterion("unit_price <>", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceGreaterThan(Double value) {
            addCriterion("unit_price >", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("unit_price >=", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceLessThan(Double value) {
            addCriterion("unit_price <", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceLessThanOrEqualTo(Double value) {
            addCriterion("unit_price <=", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIn(List<Double> values) {
            addCriterion("unit_price in", values, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotIn(List<Double> values) {
            addCriterion("unit_price not in", values, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceBetween(Double value1, Double value2) {
            addCriterion("unit_price between", value1, value2, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotBetween(Double value1, Double value2) {
            addCriterion("unit_price not between", value1, value2, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_commodity_model
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_commodity_model
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}