server:
  port: 8085

spring:
  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: Consumers
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://127.0.0.1:2181
      check: false
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20881
    scan: com.guo.consumer  #服务暴露与发现消费所在的package
    consumer:
      check: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tx-manager?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

# 默认之配置为TM的本机默认端口
#tx-lcn:
#  client:
#  manager-address: 127.0.0.1:8070

logging:
  level:
    com:
      codingapi:
        txlcn: DEBUG

# 开启日志,默认为false
tx-lcn:
  logger:
    enabled: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/tx-manager?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root