package com.guo.commodity.dao;

import com.guo.client.model.commodity.CommodityDO;
import com.guo.client.model.commodity.CommodityDOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CommodityDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity
     *
     * @mbg.generated
     */
    long countByExample(CommodityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity
     *
     * @mbg.generated
     */
    int deleteByExample(CommodityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity
     *
     * @mbg.generated
     */
    int insert(CommodityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity
     *
     * @mbg.generated
     */
    int insertSelective(CommodityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity
     *
     * @mbg.generated
     */
    List<CommodityDO> selectByExample(CommodityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity
     *
     * @mbg.generated
     */
    CommodityDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CommodityDO record, @Param("example") CommodityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CommodityDO record, @Param("example") CommodityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CommodityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CommodityDO record);

    List<CommodityDO> queryAllBySellerId(String sellerId);
}