package com.guo.stock.dao;

import com.guo.client.model.stock.StockDO;
import com.guo.client.model.stock.StockDOExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface StockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock
     *
     * @mbg.generated
     */
    long countByExample(StockDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock
     *
     * @mbg.generated
     */
    int deleteByExample(StockDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock
     *
     * @mbg.generated
     */
    int insert(StockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock
     *
     * @mbg.generated
     */
    int insertSelective(StockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock
     *
     * @mbg.generated
     */
    List<StockDO> selectByExample(StockDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock
     *
     * @mbg.generated
     */
    StockDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StockDO record, @Param("example") StockDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StockDO record, @Param("example") StockDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StockDO record);

    List<StockDO> queryAllByCommodityId(String commodityId);

    StockDO queryOneByCommodityModelId(String commodityModelId);
}