package com.guo.client.model.stock;

import java.io.Serializable;
import java.util.Date;

public class StockDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock.stock_id
     *
     * @mbg.generated
     */
    private String stockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock.seller_id
     *
     * @mbg.generated
     */
    private String sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock.commodity_id
     *
     * @mbg.generated
     */
    private String commodityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock.commodity_model_id
     *
     * @mbg.generated
     */
    private String commodityModelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock.total
     *
     * @mbg.generated
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock.total_surplus
     *
     * @mbg.generated
     */
    private Integer totalSurplus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_stock
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock.id
     *
     * @return the value of t_stock.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock.id
     *
     * @param id the value for t_stock.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock.stock_id
     *
     * @return the value of t_stock.stock_id
     *
     * @mbg.generated
     */
    public String getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock.stock_id
     *
     * @param stockId the value for t_stock.stock_id
     *
     * @mbg.generated
     */
    public void setStockId(String stockId) {
        this.stockId = stockId == null ? null : stockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock.seller_id
     *
     * @return the value of t_stock.seller_id
     *
     * @mbg.generated
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock.seller_id
     *
     * @param sellerId the value for t_stock.seller_id
     *
     * @mbg.generated
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId == null ? null : sellerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock.commodity_id
     *
     * @return the value of t_stock.commodity_id
     *
     * @mbg.generated
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock.commodity_id
     *
     * @param commodityId the value for t_stock.commodity_id
     *
     * @mbg.generated
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId == null ? null : commodityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock.commodity_model_id
     *
     * @return the value of t_stock.commodity_model_id
     *
     * @mbg.generated
     */
    public String getCommodityModelId() {
        return commodityModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock.commodity_model_id
     *
     * @param commodityModelId the value for t_stock.commodity_model_id
     *
     * @mbg.generated
     */
    public void setCommodityModelId(String commodityModelId) {
        this.commodityModelId = commodityModelId == null ? null : commodityModelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock.total
     *
     * @return the value of t_stock.total
     *
     * @mbg.generated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock.total
     *
     * @param total the value for t_stock.total
     *
     * @mbg.generated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock.total_surplus
     *
     * @return the value of t_stock.total_surplus
     *
     * @mbg.generated
     */
    public Integer getTotalSurplus() {
        return totalSurplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock.total_surplus
     *
     * @param totalSurplus the value for t_stock.total_surplus
     *
     * @mbg.generated
     */
    public void setTotalSurplus(Integer totalSurplus) {
        this.totalSurplus = totalSurplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock.status
     *
     * @return the value of t_stock.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock.status
     *
     * @param status the value for t_stock.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock.create_time
     *
     * @return the value of t_stock.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock.create_time
     *
     * @param createTime the value for t_stock.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock.update_time
     *
     * @return the value of t_stock.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock.update_time
     *
     * @param updateTime the value for t_stock.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}